# Generated by Django 4.2.5 on 2023-09-10 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employe', '0005_alter_employe_adresse_alter_employe_email_and_more'),
        ('Congé', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('Num_dem', models.AutoField(primary_key=True, serialize=False)),
                ('Etat', models.BooleanField()),
                ('CIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employe.employe')),
                ('Code_cong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Congé.congé')),
            ],
        ),
    ]
