# Generated by Django 4.2.5 on 2023-09-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employe', '0004_alter_employe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='Adresse',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='Mot_de_passe',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='Nom_utilisateur',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='Tel',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
