# Generated by Django 4.2.5 on 2023-09-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congé',
            fields=[
                ('Code_conge', models.AutoField(primary_key=True, serialize=False)),
                ('Date_debut', models.DateField()),
                ('Date_fin', models.DateField()),
            ],
        ),
    ]
