# Generated by Django 4.2.5 on 2023-09-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('CIN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Tel', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Adresse', models.CharField(max_length=100)),
                ('Salaire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Date_embauche', models.DateField()),
                ('Nom_utilisateur', models.CharField(max_length=50)),
                ('Mot_de_passe', models.CharField(max_length=50)),
                ('Sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
            ],
        ),
    ]
