# Generated by Django 4.2.5 on 2023-09-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employe', '0003_alter_employe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
