# Generated by Django 4.2.5 on 2023-09-10 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Congé', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('Num_type', models.AutoField(primary_key=True, serialize=False)),
                ('Libelle', models.CharField(max_length=20, unique=True)),
                ('Code_conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Congé.congé')),
            ],
        ),
    ]
