# Generated by Django 4.2.5 on 2023-09-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Type', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='Code_conge',
            new_name='conge',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='Num_type',
            new_name='id',
        ),
    ]
