# Generated by Django 4.2.5 on 2023-09-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Type', '0002_rename_code_conge_type_conge_rename_num_type_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='conge',
            new_name='Code_congé',
        ),
    ]
