# Generated by Django 4.2.5 on 2023-09-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0002_rename_code_cong_demande_congé_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='employe',
            new_name='CIN',
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='congé',
            new_name='code_congé',
        ),
    ]
